# docker-compose.yml - Frontend Services Only
# Este arquivo contém apenas os serviços necessários para o frontend
# O backend (auth) deve ser executado separadamente
services:
  # Frontend Development App (exemplo React/Next.js)
  frontend:
    build:
      context: ../frontend-test  # ajuste o caminho conforme necessário
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      # URLs apontando para o backend rodando separadamente
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:9998
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ1MTk2NjY2LCJleHAiOjE5NjA3NzI2NjZ9
      # Outras variáveis de frontend
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ../frontend-test:/app
      - /app/node_modules
    restart: unless-stopped
    
  # Serviço de mail para desenvolvimento (pode ser útil para testar emails)
  mail:
    image: phamhieu/inbucket:latest
    ports:
      - '2500:2500' # SMTP
      - '9000:9000' # web interface - acesse http://localhost:9000 para ver emails
      - '1100:1100' # POP3
    restart: unless-stopped
